services:
  frontend:
    build: ./aifred-client
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - APP_ENV=development
    volumes:
      - ./app:/app
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: ./app/Dockerfile.worker
    environment:
      - APP_ENV=development
    volumes:
      - ./app:/app
    depends_on:
      - web
  # init:
  #   build:
  #     context: .
  #     dockerfile: ./app/Dockerfile.init
  #   environment:
  #     - APP_ENV=development
  #   volumes:
  #     - ./app:/app
  #   depends_on:
  #     - redis
  #     - web
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
